"""add_shortage_dismissed_to_order_items

Revision ID: 33ba84dc2a2d
Revises: cb3b9b27cbe8
Create Date: 2026-01-13 17:21:54.661222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ba84dc2a2d'
down_revision: Union[str, None] = 'cb3b9b27cbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('shortage_dismissed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'shortage_dismissed')
    # ### end Alembic commands ###
