"""Add indexes to order_items

Revision ID: cb3b9b27cbe8
Revises: f456e30a4ade
Create Date: 2026-01-08 19:34:44.703511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3b9b27cbe8'
down_revision: Union[str, None] = 'f456e30a4ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_items_inventory_item_id'), 'order_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_order_items_supplier_id'), 'order_items', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_supplier_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_inventory_item_id'), table_name='order_items')
    # ### end Alembic commands ###
