"""add issue_photo_url to order_items

Revision ID: f456e30a4ade
Revises: 
Create Date: 2025-12-16 14:17:57.175261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f456e30a4ade'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_items_subcategory'), 'inventory_items', ['subcategory'], unique=False)
    op.add_column('order_items', sa.Column('issue_photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'issue_photo_url')
    op.drop_index(op.f('ix_inventory_items_subcategory'), table_name='inventory_items')
    # ### end Alembic commands ###
